---
- hosts: all
  become: yes
  tasks:
    - name: Install required software
      apt:
        name:
          - nodejs
          - npm
          - nginx
        state: latest

    - name: Clone project repository
      git:
        repo: 'https://github.com/Creed128/online-notizbuch.git'
        dest: /var/www/yourproject
        version: master

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Install Node.js project dependencies
      npm:
        path: "/var/www/yourproject"

    - name: Start the Node application with PM2
      command: pm2 start /var/www/yourproject/app.js --name your-app

    - name: Configure nginx as a reverse proxy
      blockinfile:
        path: /etc/nginx/sites-available/default
        block: |
          server {
            listen 80;
            server_name yourdomain.com;

            location / {
              proxy_pass http://localhost:3000;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
            }
          }

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted

    - name: Ensure application starts on reboot
      command: pm2 startup systemd
